/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
//
//#include "main.h"
/*
 * main.h
 *
 *  Created on: Sep 24, 2026
 *      Author: Mahesh Bavage
 */
#ifndef MAIN_H_
#define MAIN_H_

//#include <stdint.h>

// Peripheral base address//
#define PERIPH_BASE 0x40000000UL
#define APB1PERIPH_BASE (PERIPH_BASE + 0x00000000UL)
#define AHB1PERIPH_BASE (PERIPH_BASE + 0x00020000UL)

#define RCC_BASE            (AHB1PERIPH_BASE + 0x3800UL)
#define GPIOB_BASE          (AHB1PERIPH_BASE + 0x0400UL)
#define I2C1_BASE 			(APB1PERIPH_BASE + 0x5400UL)

#define RCC     ((RCC_TypeDef *) RCC_BASE)
#define GPIOB   ((GPIO_TypeDef *) GPIOB_BASE)
#define I2C1     ((I2C_TypeDef*) I2C1_BASE)
#define GPIOBEN (1U << 1U)
#define I2C1EN (1U << 21U)

#define PB8_MODER (3U << 16U)
#define PB8_AF (2U << 16U)
#define PB9_MODER (3U << 18U)
#define PB9_AF (2U << 18U)
#define PB8_OTYPER (1U << 8U)
#define PB9_OTYPER (1U << 9U)
#define PB8_PUPDR (3U << 16U)
#define PB8_PU (1U << 16U)
#define PB9_PUPDR (3U << 18U)
#define PB9_PU (1U << 18U)

#define PB8_AF_MASK (0xFU << 0U)
#define PB9_AF_MASK (0xFU << 4U)

#define PB8_AF4 (4U << 0U)
#define PB9_AF4 (4U << 4U)

#define I2C1_CR1_PE (1U << 0U)
#define I2C1_CR1_START (1U << 8U)

#define I2C1_CR2_FREQ_MASK (0x3FU)
#define I2C1_CR2_FREQ (16U)
#define I2C1_CCR (80U)
#define I2C1_TRISE (17U)

#define I2C_CR1_START (1U << 8U)

void I2C1_Start(void);

typedef struct{
	volatile uint32_t MODER;
	volatile uint32_t OTYPER;
	volatile uint32_t OSPEEDER;
	volatile uint32_t PUPDR;
	volatile uint32_t IDR;
	volatile uint32_t ODR;
	volatile uint32_t BSRR;
	volatile uint32_t LCKR;
	volatile uint32_t AFRL;
	volatile uint32_t AFRH;
}GPIO_TypeDef;

typedef struct {
	volatile uint32_t CR1;
	volatile uint32_t CR2;
	volatile uint32_t OAR1;
	volatile uint32_t OAR2;
	volatile uint32_t DR;
	volatile uint32_t SR1;
	volatile uint32_t SR2;
	volatile uint32_t CCR;
	volatile uint32_t TRISE;
	volatile uint32_t FLTR;
}I2C_TypeDef;

typedef struct{
	volatile uint32_t CR;
	volatile uint32_t PLLCFGR;
	volatile uint32_t CFGR;
	volatile uint32_t CIR;
	volatile uint32_t AHB1RSTR;
	volatile uint32_t AHB2RSTR;
	volatile uint32_t AHB3RSTR;
	uint32_t RESERVED0;
	volatile uint32_t APB1RTR;
	volatile uint32_t APB2RSTR;
	uint32_t RESERVED1[2];
	volatile uint32_t AHB1ENR;
	volatile uint32_t AHB2ENR;
	volatile uint32_t AHB3ENR;
	uint32_t RESERVED2;
	volatile uint32_t APB1ENR;
	volatile uint32_t APB2ENR;
	uint32_t RESERVED3[2];
	volatile uint32_t AHB1LPENR;
	volatile uint32_t AHB2LPENR;
	volatile uint32_t AHB3LPENR;
	uint32_t RESERVED4;
	volatile uint32_t APB1LPENR;
	volatile uint32_t APB2LPENR;
	uint32_t RESERVED5[2];
	volatile uint32_t BDCR;
	volatile uint32_t CSR;
	uint32_t RESERVED6[2];
	volatile uint32_t SSCGR;
	volatile uint32_t PLLI2SCFGR;
	volatile uint32_t PLLSAICFGR;
	volatile uint32_t DCKCFGR;
	volatile uint32_t CKGATENR;
	volatile uint32_t DCKCFGR2;
}RCC_TypeDef;
#endif /* MAIN_H_ */
