/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"
//
//#include "main.h"
/*
 * main.h
 *
 *  Created on: Sep 24, 2026
 *      Author: Mahesh Bavage
 */


//#include <stdint.h>

// Peripheral base address//


//int main(void);

int main(void)
{
	RCC->AHB1ENR |= GPIOBEN;
	RCC->APB1ENR |= I2C1EN;

	GPIOB->MODER &= ~PB8_MODER;
	GPIOB->MODER |= PB8_AF;
	GPIOB->MODER &= ~PB9_MODER;
	GPIOB->MODER |= PB9_AF;
	GPIOB->OTYPER |= PB8_OTYPER;
	GPIOB->OTYPER |= PB9_OTYPER;
	GPIOB->PUPDR &= ~PB8_PUPDR;
	GPIOB->PUPDR |= PB8_PU;
	GPIOB->PUPDR &= ~PB9_PUPDR;
	GPIOB->PUPDR |= PB9_PU;
	GPIOB->AFRH &= ~PB8_AF_MASK;
	GPIOB->AFRH |= PB8_AF4;
	GPIOB->AFRH &= ~PB9_AF_MASK;
	GPIOB->AFRH |= PB9_AF4;

	I2C1->CR1 &= ~I2C1_CR1_PE;
	//I2C1->CR1 &= I2C1_CR1_PE;

	I2C1->CR2 &= ~I2C1_CR2_FREQ_MASK;
	I2C1->CR2 |= I2C1_CR2_FREQ;

	I2C1->CCR = I2C1_CCR;
	I2C1->TRISE = I2C1_TRISE;

	I2C1->CR1 |= I2C1_CR1_PE;

	I2C1_Start();
	while(1)
	{
	}
}
volatile uint32_t start_done = 0;

void I2C1_Start(void)
{
    I2C1->CR1 |= I2C1_CR1_START;

    while (!(I2C1->SR1 & (1U << 0U)))
    {
    }

    start_done = 1;
}


//volatile uint32_t start_done = 0;
//volatile uint32_t start_timeout = 0;
//
//void I2C1_Start(void)
//{
//    I2C1->CR1 |= I2C_CR1_START;
//
//    while (!(I2C1->SR1 & (1U << 0U)))
//    {
//        start_timeout++;
//
//        if (start_timeout > 100000)
//        {
//            start_done = 2;
//            return;
//        }
//    }
//
//    start_done = 1;
//}
